version: '3.8'

services:
  scs-data-management:
    build: .
    container_name: scs-data-management
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - FRONTEND_URL=http://localhost:3000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./app:/app/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s